### PR TITLE
Fix Wrong Timestamps

### LINKED ISSUE #93: Bug: wrong timestamps on multirecordings
## Description

Sometimes we save the wrong timestamp when changing the label during the recording. Below I added an example that can be reproduced.

## Must Include

- [x] Fix

## Notes

If you select the first activity in your list and the first person, then start a recording and at 2 seconds start to change the label. After waiting for some more seconds you change the label to something else and the timestamp of the change will be further in the future.
eg. start select at 2 sec, choose at 4 sec -> timestamp at 6 or 8 sec

### PR DESCRIPTION
**Pull request by kpostnov**
Fixes #93.

Error caused by deleting import lines in a previous merge.

### CODE REVIEW

File: app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt [hunk 1]
```diff
@@ -148,6 +148,16 @@ class LoggingManager(
     }
 
     private fun startLogging() {
+        while (labels.size > 1) {
+            labels.removeAt(0)
+        }
```
Comment (FranzSw) [inline app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt:153]: Labels are cleared in `stopLogging()`, why do we need this?

Comment (FranzSw) [reply app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt:153]: Hm, okay, I see (when labels are picked during no active recording, the labels array is still filled). I think a comment would be helpful if not extract the new code into a new method so that it is

```
recordingStartTime = System.currentTimeMillis()
initializeLabels(recordingStartTime)
```

Wdyt?

all in all this method is pretty complex and tightly coupled

Comment (tfiedlerdev) [reply app/src/main/java/sensors_in_paradise/sonar/page2/LoggingManager.kt:153]: 👍

**Review by FranzSw — APPROVED** [review]
Très chic!

**Comment by FranzSw** [comment]
Ich hab ihn mal gemergt für morgen... :D
